name: 'Deploy with werf'

on:
  workflow_dispatch:
  push:
    branches:
      - test

permissions:
  contents: read
  packages: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run werf
        run: |
          . $(werf ci-env github --as-file) 
          werf converge --set dockerconfigjson="${{ secrets.DOCKER_CONFIG_BASE64 }}" --log-verbose=true
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
          WERF_ENV: test
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
